default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= Figaro.env.database_pool %>
  username: <%= Figaro.env.database_username %>
  password: <%= Figaro.env.database_password %>
  socket: <%= Figaro.env.database_socket %>

development:
  <<: *default
  database: <%= Figaro.env.databse_name %>

test:
  <<: *default
  database: <%= Figaro.env.database_name_test %>
